### ISSUE TITLE
error in make step

### ISSUE THREAD

**Issue by kndol** [cogniti/nimf#32]
I'm using Ubuntu 16.10.
Error occurred in make step. Error messages are:

  GISCAN   Nimf-2016.09.gir
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/lib/i386-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 544, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "/usr/lib/i386-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 421, in create_binary
    shlibs = resolve_shlibs(options, binary, options.libraries)
  File "/usr/lib/i386-linux-gnu/gobject-introspection/giscanner/shlibs.py", line 146, in resolve_shlibs
    _resolve_non_libtool(options, binary, non_libtool))
  File "/usr/lib/i386-linux-gnu/gobject-introspection/giscanner/shlibs.py", line 119, in _resolve_non_libtool
    line = line.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 29: ordinal not in range(128)
/usr/share/gobject-introspection-1.0/Makefile.introspection:155: 'Nimf-2016.09.gir' 타겟에 대한 명령이 실패했습니다
make[3]: *** [Nimf-2016.09.gir] 오류 1

**Comment by cogniti** [comment]
Try to compile in an English environment.

**Comment by cogniti** [comment]
As it seams not to be a bug in Nimf I close this issue. Please refer to the following.

https://bugs.archlinux.org/task/51578

https://bugzilla.gnome.org/show_bug.cgi?id=774999
